### ISSUE TITLE
Word mapping links

### ISSUE THREAD

**Issue by sarpulhu** [jimpudar/bip39-dice#1]
Both links for diceware are set up wrong. They split words unevenly. Heads and Tails have different size lists so odds are not the same. My dicebip39 works perfectly and eliminates perfectly fair.

**Comment by jimpudar** [comment]
I see your point when the first "roll" is a coin flip and there are more words mapped to heads than to tails, but I am pretty certain the generated mapper I have in this repo is not flawed. 

I see in your repo, you are essentially mapping the entire space of four-sided dice to the word list. In my version, if you end up with a roll that is "too high", you re-roll **all the dice** until you get a complete roll of N dice which maps to the words. 

AFAICT, no word is more likely than any other, but then again I failed statistics in college :)

**Comment by jimpudar** [comment]
Updated the README to point to your repo
